/**
 * Seed posts — the frontend's 4 seeds plus ~11 more, written in Haven's tone
 * (gentle, honest, no toxic positivity). Times are relative to server start
 * so the recency signal always has something to work with.
 */

import { Post } from './types.js';

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString();

export function buildSeedPosts(): Post[] {
  return [
    // --- The 4 posts mirroring the frontend seeds ---
    {
      id: 'seed-1',
      author: 'QuietRiver',
      avatarColor: '#7fb3a3',
      createdAt: hoursAgo(2),
      moodChip: 'Feeling heavy',
      title: 'Today was a lot',
      body: 'Woke up already tired. Managed a short walk and one proper meal, and I am trying to count that as enough.',
      hugs: 14,
      replies: 6,
    },
    {
      id: 'seed-2',
      author: 'SoftLantern',
      avatarColor: '#e8b4b8',
      createdAt: hoursAgo(5),
      moodChip: 'Hopeful',
      title: 'A small thing that helped',
      body: 'I started writing one sentence each night about something that did not hurt. Some nights it is just "the tea was warm". It adds up.',
      hugs: 22,
      replies: 9,
    },
    {
      id: 'seed-3',
      author: 'MossAndStone',
      avatarColor: '#a3c9a8',
      createdAt: hoursAgo(9),
      moodChip: 'Calm',
      title: 'Rainy day reset',
      body: 'Gave myself permission to do nothing productive today. Sat by the window, watched the rain, breathed. No guilt this time.',
      hugs: 11,
      replies: 4,
    },
    {
      id: 'seed-4',
      author: 'GoldenHour',
      avatarColor: '#f0c987',
      createdAt: hoursAgo(1),
      moodChip: 'Great',
      title: 'Six months of therapy today',
      body: 'I cried at my first session and could not say why. Today I laughed. If you are at the beginning: it is worth staying.',
      hugs: 31,
      replies: 12,
    },
    // --- Additional Haven-toned posts ---
    {
      id: 'seed-5',
      author: 'NightOwlNest',
      avatarColor: '#9aa5ce',
      createdAt: hoursAgo(3),
      moodChip: 'Anxious',
      title: '3am brain again',
      body: 'My mind keeps rehearsing conversations that will never happen. Does anyone have a way of powering down that actually works?',
      hugs: 17,
      replies: 11,
    },
    {
      id: 'seed-6',
      author: 'WarmMug',
      avatarColor: '#d4a373',
      createdAt: hoursAgo(7),
      moodChip: 'Hopeful',
      title: 'Asked for help today',
      body: 'I told my sister I am not okay. My hands were shaking the whole time. She just held me. Asking was the hardest and best thing.',
      hugs: 40,
      replies: 15,
    },
    {
      id: 'seed-7',
      author: 'FernShadow',
      avatarColor: '#6d8f7b',
      createdAt: hoursAgo(14),
      moodChip: 'Feeling heavy',
      title: 'Grief is quiet today',
      body: 'Two years since we lost dad. Some days it is a whisper, some days a siren. Today it is quiet, and somehow that is harder.',
      hugs: 26,
      replies: 13,
      contentWarning: 'Grief and loss',
    },
    {
      id: 'seed-8',
      author: 'PaperBoat',
      avatarColor: '#89b0ae',
      createdAt: hoursAgo(4),
      moodChip: 'Calm',
      title: 'Five slow breaths',
      body: 'In for four, hold for four, out for six. Did it five times before my meeting. It did not fix anything, but my shoulders dropped an inch.',
      hugs: 9,
      replies: 3,
    },
    {
      id: 'seed-9',
      author: 'QuietRiver',
      avatarColor: '#7fb3a3',
      createdAt: hoursAgo(20),
      moodChip: 'Anxious',
      title: 'Doctor appointment tomorrow',
      body: 'Nervous about finally talking to my GP about my low moods. Writing down what I want to say so I do not freeze. Wish me steadiness.',
      hugs: 19,
      replies: 8,
    },
    {
      id: 'seed-10',
      author: 'SteadyPine',
      avatarColor: '#557c83',
      createdAt: hoursAgo(6),
      title: 'Just checking in',
      body: 'No big story today. I am here, I am reading your posts, and I am sending quiet strength to everyone who needs it tonight.',
      hugs: 33,
      replies: 7,
    },
    {
      id: 'seed-11',
      author: 'EmberGlow',
      avatarColor: '#c98a6b',
      createdAt: hoursAgo(30),
      moodChip: 'Feeling heavy',
      title: 'The dark thoughts are loud tonight',
      body: 'Having thoughts of self-harm again. I am safe, I have my crisis plan and my sister is awake. I just needed to say it somewhere honest.',
      hugs: 52,
      replies: 24,
      contentWarning: 'Mentions of self-harm',
    },
    {
      id: 'seed-12',
      author: 'WillowWren',
      avatarColor: '#b5c99a',
      createdAt: hoursAgo(11),
      moodChip: 'Great',
      title: 'I cooked a real meal!',
      body: 'After weeks of toast and cereal, I made an actual dinner with vegetables. It even tasted good. Small wins are still wins.',
      hugs: 27,
      replies: 10,
    },
    {
      id: 'seed-13',
      author: 'DuskFox',
      avatarColor: '#a17c6b',
      createdAt: hoursAgo(16),
      moodChip: 'Anxious',
      title: 'Work anxiety spiral',
      body: 'Made a mistake in front of the team and my brain says everyone hates me now. Logically I know that is not true. Logic is not winning.',
      hugs: 13,
      replies: 9,
    },
    {
      id: 'seed-14',
      author: 'CloudKettle',
      avatarColor: '#8faadc',
      createdAt: hoursAgo(26),
      moodChip: 'Hopeful',
      title: 'One year clean from the bottle',
      body: 'A year ago I could not imagine one sober day. There were relapses before this streak. Be patient with yourself; the path is not straight.',
      hugs: 48,
      replies: 18,
      contentWarning: 'Alcohol recovery',
    },
    {
      id: 'seed-15',
      author: 'PebblePath',
      avatarColor: '#c0b8a8',
      createdAt: hoursAgo(8),
      moodChip: 'Calm',
      title: 'Sunday gentleness',
      body: 'Clean sheets, open window, phone on silent. Protecting this small pocket of peace like it is sacred, because it is.',
      hugs: 15,
      replies: 5,
    },
  ];
}
